name: Build and Release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Build React app
        env:
          CI: false
        run: npm run build
        
      - name: Build Electron app
        if: matrix.os != 'ubuntu-latest'
        run: npm run electron-build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron app (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          npm run electron-build
          # Remove chrome-sandbox from both unpacked and packaged versions
          rm -f dist/linux-unpacked/chrome-sandbox
          cd dist
          tar xzf drivechain-launcher-*.tar.gz
          rm -f drivechain-launcher-*/chrome-sandbox
          tar czf drivechain-launcher-*.tar.gz drivechain-launcher-*/
          rm -rf drivechain-launcher-*/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            dist/drivechain-launcher-*.tar.gz
          
      - name: Upload Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist/Drivechain-Launcher-Setup-*.exe
          
      - name: Upload macOS artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            dist/Drivechain-Launcher-*-x64.dmg
            dist/Drivechain-Launcher-*-arm64.dmg
